name: Docker Build and Push  

on:  
  push:  
    branches: [master]  

jobs:  
  build-and-push:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Clonar el repositorio  
        uses: actions/checkout@v3  

      - name: Iniciar sesión en Docker Hub  
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      - name: Construir la imagen Docker  
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculadora .  

      - name: Etiquetar la imagen  
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/calculadora ${{ secrets.DOCKER_USERNAME }}/calculadora:latest  

      - name: Subir la imagen a Docker Hub  
        run: docker push ${{ secrets.DOCKER_USERNAME }}/calculadora:latest  
